# Possible data types are bool, int, float, long, double, and long double.



In [8]:
import numpy as np

In [9]:
# numpy arrays

In [10]:
# creating arrays
a=np.array([2,4,6,8,10])
print(a)

[ 2  4  6  8 10]


In [11]:
# another way to create an array using arrange()
a=np.arange(1,11)
print(a) # not arrange arange and step is by default 1
# generral form of arnage(start,[stop],step)
#The stop parameteris compulsory

[ 1  2  3  4  5  6  7  8  9 10]


In [12]:
# apart from array and arange,there are other options such as 
#zeros()-->creates an array for a given dimension wih all zeroes

#ones()--> ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,all ones
#fulls()-->generae an array with constant values

#random()---> crates na array with any given dimenion

# eyes()--->create ana identity matrix

In [13]:

np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [14]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.full((6,6),11)

array([[11, 11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11, 11]])

In [16]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [17]:
np.random.random((3,3)) # with values ranging from 0 to1

array([[0.11006753, 0.15817277, 0.57161048],
       [0.46761321, 0.91919242, 0.1690921 ],
       [0.00844431, 0.85012672, 0.21500028]])

In the preceding code, we have seen some built-in functions for creating arrays with allzero values, all-one values, and all-constant values. After that, we have created the identity
matrix using the eye() function and a random matrix using the random.random()
function. Let's see some other array features in the next section.

# array features

 #  NumPy arrays are a homogeneous kind of data structure that has the same types of items.

## Another benefit of NumPy arrays is to offer vectorized operations instead of
## iterating each item and performing operations on it. NumPy arrays are indexed just like a
## Python list and start from 0. NumPy uses an optimized C API for the fast processing of the
## array operations.


In [18]:
a=np.arange(1,11)
print(type(a))
print(a.dtype)

<class 'numpy.ndarray'>
int32


# When you use type(), it returns numpy.ndarray. This means that the type() function
# returns the type of the container. When you use dtype(), it will return int64, since it is
# the type of the elements. You may also get the output as int32 if you are using 32-bit
# Python. Both cases use integers (32- and 64-bit). One-dimensional NumPy arrays are also
# known as vectors

In [19]:
# Shape of the vector
print(a.shape)

# the vector has 10 elements with values ranging from 1 to 10. The shape
#property of the array is a tuple; in this instance, it is a tuple of one element, which holds the
#length in each dimension

(10,)


# Selecting array elements

In [20]:
a=np.array([[5,6],[8,9]])

In [21]:
print(a)

[[5 6]
 [8 9]]


In [22]:
#In the preceding example, the matrix is created using the array() function with the inputlist of lists.


In [23]:
# a[m,n]
#Here, m is the row index and n is the column index of the matrix.

In [24]:
print(a[0,0])

5


In [25]:
print(a[1,1])

9


In [26]:
print(a.shape)

(2, 2)


In [27]:
 # numpy array numerical data types

In [28]:
# Python offers three types of numerical data types: integer type, float type, and complex type

In [29]:
# NumPy offers a bulk of data types with mathematical types and numbers.

In [30]:
'''
Data Type Details
bool This is a Boolean type that stores a bit and takes True or False
values.
inti Platform integers can be either int32 or int64.
int8 Byte store values range from -128 to 127.
int16 This stores integers ranging from -32768 to 32767.
int32 This stores integers ranging from -2 ** 31 to 2 ** 31 -1.
int64 This stores integers ranging from -2 ** 63 to 2 ** 63 -1.
uint8 This stores unsigned integers ranging from 0 to 255.
uint16 This stores unsigned integers ranging from 0 to 65535.
uint32 This stores unsigned integers ranging from 0 to 2 ** 32 – 1.
uint64 This stores unsigned integers ranging from 0 to 2 ** 64 – 1.
float16 Half-precision float; sign bit with 5 bits exponent and 10 bits
mantissa.
float32 Single-precision float; sign bit with 8 bits exponent and 23 bits
mantissa.
float64 or float Double-precision float; sign bit with 11 bits exponent and 52 bits
mantissa.
complex64 Complex number stores two 32-bit floats: real and imaginary
number.
complex128 orcomplex
Complex number stores two 64-bit floats: real and imaginary
number.
'''

'\nData Type Details\nbool This is a Boolean type that stores a bit and takes True or False\nvalues.\ninti Platform integers can be either int32 or int64.\nint8 Byte store values range from -128 to 127.\nint16 This stores integers ranging from -32768 to 32767.\nint32 This stores integers ranging from -2 ** 31 to 2 ** 31 -1.\nint64 This stores integers ranging from -2 ** 63 to 2 ** 63 -1.\nuint8 This stores unsigned integers ranging from 0 to 255.\nuint16 This stores unsigned integers ranging from 0 to 65535.\nuint32 This stores unsigned integers ranging from 0 to 2 ** 32 – 1.\nuint64 This stores unsigned integers ranging from 0 to 2 ** 64 – 1.\nfloat16 Half-precision float; sign bit with 5 bits exponent and 10 bits\nmantissa.\nfloat32 Single-precision float; sign bit with 8 bits exponent and 23 bits\nmantissa.\nfloat64 or float Double-precision float; sign bit with 11 bits exponent and 52 bits\nmantissa.\ncomplex64 Complex number stores two 32-bit floats: real and imaginary\nnumber.\nc

In [31]:
# for each data type there exists a matchin gconversion function

In [32]:
np.float64(21)

21.0

In [36]:
np.int8(44.0)

44

In [37]:
np.bool(21)

C:\Users\karti\AppData\Local\Temp/ipykernel_11184/3666456476.py:1: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.bool(21)


True

In [38]:
np.float16(True)

1.0

In [39]:
# many functions have a dtype argument which is frequently optional

In [40]:
"""
It is important to be aware that you are not allowed to change a complex number into an
integer. If you try to convert complex data types into integers, then you will get
TypeError."""

'\nIt is important to be aware that you are not allowed to change a complex number into an\ninteger. If you try to convert complex data types into integers, then you will get\nTypeError.'

In [44]:
c=complex(23,27)
c.real,c.imag

(23.0, 27.0)

In [42]:
c

(90+70j)

In [45]:
arr=np.arange(1,11,dtype=np.float32)

# dtype objects

In [49]:
a=np.array([3,2,2,3,2,3,23])
a.dtype,a.dtype.itemsize

(dtype('int32'), 4)

In [50]:
# dtype objects also tell us the size of the data type in bytes using the itemsize property

# Manipulating array shapes

In [51]:
# learn new numpy funcions
# uch as
# reshape() flatten() ravel() transpose()  and resize() 

In [52]:
# reshape will change the shape of the array

In [57]:
arr=np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [58]:
arr.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [59]:
arr.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [60]:
# another operation is flatten()
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

The ravel() function is similar to the flatten() function. It also transforms an
n-dimensional array into a one-dimensional array. The main difference is that
flatten() returns the actual array while ravel() returns the reference of the
original array. The ravel() function is faster than the flatten() function
because it does not occupy extra memory:

In [69]:
arr.reshape(4,3)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [63]:

arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

The transpose() function is a linear algebraic function that transposes the
given two-dimensional matrix. The word transpose means converting rows into
columns and columns into rows:

In [76]:
ui=arr.reshape(3,4)
print(ui)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [71]:
art=np.array([[23,23,23],[23232,232,23]])

In [72]:
art

array([[   23,    23,    23],
       [23232,   232,    23]])

In [73]:
print(art)

[[   23    23    23]
 [23232   232    23]]


The resize() function changes the size of the NumPy array. It is similar to
reshape() but it changes the shape of the original array:

In [77]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [78]:
arr.resize(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


# the stacking of numpy arrays

Stacking means joining the same dimensional arrays along
with a new axis. Stacking can be done horizontally, vertically, column-wise, row-wise, or
depth-wise:


Horizontal stacking: In horizontal stacking, the same dimensional arrays are
joined along with a horizontal axis using the hstack() and concatenate()
functions. Let's see the following example:


In [79]:
arr1=np.arange(1,10).reshape(3,3)

In [80]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [81]:
arr2=3*arr1

In [82]:
arr2

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [84]:
# horizontal stacking
arr3=np.hstack((arr1,arr2))
print(arr3)

[[ 1  2  3  3  6  9]
 [ 4  5  6 12 15 18]
 [ 7  8  9 21 24 27]]


In the preceding code, two arrays are stacked horizontally along the x axis. The
concatenate() function can also be used to generate the horizontal stacking
with axis parameter value 1:


In [85]:
arr4=np.concatenate((arr1,arr2),axis=1)
print(arr4)

[[ 1  2  3  3  6  9]
 [ 4  5  6 12 15 18]
 [ 7  8  9 21 24 27]]


In [86]:
#vertical stacking
arr5=np.vstack((arr1,arr2))
print(arr5)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [87]:
#using concatenate
arr6=np.concatenate((arr1,arr2),axis=0)

In [88]:
arr6

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

# depth Stacking
In depth stacking, the same dimensional arrays are joined along
with a third axis (depth) using the dstack() function. Let's see the following
example:

In [90]:
arr7=np.dstack((arr1,arr2))
print(arr7)

[[[ 1  3]
  [ 2  6]
  [ 3  9]]

 [[ 4 12]
  [ 5 15]
  [ 6 18]]

 [[ 7 21]
  [ 8 24]
  [ 9 27]]]


Column stacking: Column stacking stacks multiple sequence one-dimensional
arrays as columns into a single two-dimensional array. Let's see an example of
column stacking:


In [92]:
arr1=np.arange(4,7)
arr1

array([4, 5, 6])

In [93]:
arr2=2*arr1
print(arr2)

[ 8 10 12]


In [94]:
arrcolstack=np.column_stack((arr1,arr2))
print(arrcolstack)

[[ 4  8]
 [ 5 10]
 [ 6 12]]


Row stacking: Row stacking stacks multiple sequence one-dimensional arrays as
rows into a single two-dimensional arrays. Let's see an example of row stacking

In [96]:
arrrowstack=np.row_stack((arr1,arr2))
print(arrrowstack)

[[ 4  5  6]
 [ 8 10 12]]


# partioning  numpy arrays opposite of stack