# Possible data types are bool, int, float, long, double, and long double.



In [2]:
import numpy as np

In [3]:
# numpy arrays

In [4]:
# creating arrays
a=np.array([2,4,6,8,10])
print(a)

[ 2  4  6  8 10]


In [5]:
# another way to create an array using arrange()
a=np.arange(1,11)
print(a) # not arrange arange and step is by default 1
# generral form of arnage(start,[stop],step)
#The stop parameteris compulsory

[ 1  2  3  4  5  6  7  8  9 10]


In [6]:
# apart from array and arange,there are other options such as 
#zeros()-->creates an array for a given dimension wih all zeroes

#ones()--> ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,all ones
#fulls()-->generae an array with constant values

#random()---> crates na array with any given dimenion

# eyes()--->create ana identity matrix

In [7]:

np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [8]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.full((6,6),11)

array([[11, 11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11, 11]])

In [10]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [11]:
np.random.random((3,3)) # with values ranging from 0 to1

array([[0.83551618, 0.39897482, 0.10705874],
       [0.67551187, 0.05483486, 0.9216072 ],
       [0.56377563, 0.80314609, 0.96154034]])

In the preceding code, we have seen some built-in functions for creating arrays with allzero values, all-one values, and all-constant values. After that, we have created the identity
matrix using the eye() function and a random matrix using the random.random()
function. Let's see some other array features in the next section.

# array features

 #  NumPy arrays are a homogeneous kind of data structure that has the same types of items.

## Another benefit of NumPy arrays is to offer vectorized operations instead of
## iterating each item and performing operations on it. NumPy arrays are indexed just like a
## Python list and start from 0. NumPy uses an optimized C API for the fast processing of the
## array operations.


In [12]:
a=np.arange(1,11)
print(type(a))
print(a.dtype)

<class 'numpy.ndarray'>
int32


# When you use type(), it returns numpy.ndarray. This means that the type() function
# returns the type of the container. When you use dtype(), it will return int64, since it is
# the type of the elements. You may also get the output as int32 if you are using 32-bit
# Python. Both cases use integers (32- and 64-bit). One-dimensional NumPy arrays are also
# known as vectors

In [13]:
# Shape of the vector
print(a.shape)

# the vector has 10 elements with values ranging from 1 to 10. The shape
#property of the array is a tuple; in this instance, it is a tuple of one element, which holds the
#length in each dimension

(10,)


# Selecting array elements

In [14]:
a=np.array([[5,6],[8,9]])

In [15]:
print(a)

[[5 6]
 [8 9]]


In [16]:
#In the preceding example, the matrix is created using the array() function with the inputlist of lists.


In [17]:
# a[m,n]
#Here, m is the row index and n is the column index of the matrix.

In [18]:
print(a[0,0])

5


In [19]:
print(a[1,1])

9


In [20]:
print(a.shape)

(2, 2)


In [21]:
 # numpy array numerical data types

In [22]:
# Python offers three types of numerical data types: integer type, float type, and complex type

In [23]:
# NumPy offers a bulk of data types with mathematical types and numbers.

In [24]:
'''
Data Type Details
bool This is a Boolean type that stores a bit and takes True or False
values.
inti Platform integers can be either int32 or int64.
int8 Byte store values range from -128 to 127.
int16 This stores integers ranging from -32768 to 32767.
int32 This stores integers ranging from -2 ** 31 to 2 ** 31 -1.
int64 This stores integers ranging from -2 ** 63 to 2 ** 63 -1.
uint8 This stores unsigned integers ranging from 0 to 255.
uint16 This stores unsigned integers ranging from 0 to 65535.
uint32 This stores unsigned integers ranging from 0 to 2 ** 32 – 1.
uint64 This stores unsigned integers ranging from 0 to 2 ** 64 – 1.
float16 Half-precision float; sign bit with 5 bits exponent and 10 bits
mantissa.
float32 Single-precision float; sign bit with 8 bits exponent and 23 bits
mantissa.
float64 or float Double-precision float; sign bit with 11 bits exponent and 52 bits
mantissa.
complex64 Complex number stores two 32-bit floats: real and imaginary
number.
complex128 orcomplex
Complex number stores two 64-bit floats: real and imaginary
number.
'''

'\nData Type Details\nbool This is a Boolean type that stores a bit and takes True or False\nvalues.\ninti Platform integers can be either int32 or int64.\nint8 Byte store values range from -128 to 127.\nint16 This stores integers ranging from -32768 to 32767.\nint32 This stores integers ranging from -2 ** 31 to 2 ** 31 -1.\nint64 This stores integers ranging from -2 ** 63 to 2 ** 63 -1.\nuint8 This stores unsigned integers ranging from 0 to 255.\nuint16 This stores unsigned integers ranging from 0 to 65535.\nuint32 This stores unsigned integers ranging from 0 to 2 ** 32 – 1.\nuint64 This stores unsigned integers ranging from 0 to 2 ** 64 – 1.\nfloat16 Half-precision float; sign bit with 5 bits exponent and 10 bits\nmantissa.\nfloat32 Single-precision float; sign bit with 8 bits exponent and 23 bits\nmantissa.\nfloat64 or float Double-precision float; sign bit with 11 bits exponent and 52 bits\nmantissa.\ncomplex64 Complex number stores two 32-bit floats: real and imaginary\nnumber.\nc

In [25]:
# for each data type there exists a matchin gconversion function

In [26]:
np.float64(21)

21.0

In [27]:
np.int8(44.0)

44

In [28]:
np.bool(21)

C:\Users\karti\AppData\Local\Temp/ipykernel_11684/3666456476.py:1: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.bool(21)


True

In [29]:
np.float16(True)

1.0

In [30]:
# many functions have a dtype argument which is frequently optional

In [31]:
"""
It is important to be aware that you are not allowed to change a complex number into an
integer. If you try to convert complex data types into integers, then you will get
TypeError."""

'\nIt is important to be aware that you are not allowed to change a complex number into an\ninteger. If you try to convert complex data types into integers, then you will get\nTypeError.'

In [32]:
c=complex(23,27)
c.real,c.imag

(23.0, 27.0)

In [33]:
c

(23+27j)

In [34]:
arr=np.arange(1,11,dtype=np.float32)

# dtype objects

In [35]:
a=np.array([3,2,2,3,2,3,23])
a.dtype,a.dtype.itemsize

(dtype('int32'), 4)

In [36]:
# dtype objects also tell us the size of the data type in bytes using the itemsize property

# Manipulating array shapes

In [37]:
# learn new numpy funcions
# uch as
# reshape() flatten() ravel() transpose()  and resize() 

In [38]:
# reshape will change the shape of the array

In [39]:
arr=np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [40]:
arr.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [41]:
arr.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
# another operation is flatten()
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

The ravel() function is similar to the flatten() function. It also transforms an
n-dimensional array into a one-dimensional array. The main difference is that
flatten() returns the actual array while ravel() returns the reference of the
original array. The ravel() function is faster than the flatten() function
because it does not occupy extra memory:

In [43]:
arr.reshape(4,3)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [44]:

arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

The transpose() function is a linear algebraic function that transposes the
given two-dimensional matrix. The word transpose means converting rows into
columns and columns into rows:

In [45]:
ui=arr.reshape(3,4)
print(ui)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [46]:
art=np.array([[23,23,23],[23232,232,23]])

In [47]:
art

array([[   23,    23,    23],
       [23232,   232,    23]])

In [48]:
print(art)

[[   23    23    23]
 [23232   232    23]]


The resize() function changes the size of the NumPy array. It is similar to
reshape() but it changes the shape of the original array:

In [49]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [50]:
arr.resize(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


# the stacking of numpy arrays

Stacking means joining the same dimensional arrays along
with a new axis. Stacking can be done horizontally, vertically, column-wise, row-wise, or
depth-wise:


Horizontal stacking: In horizontal stacking, the same dimensional arrays are
joined along with a horizontal axis using the hstack() and concatenate()
functions. Let's see the following example:


In [51]:
arr1=np.arange(1,10).reshape(3,3)

In [52]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
arr2=3*arr1

In [54]:
arr2

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [55]:
# horizontal stacking
arr3=np.hstack((arr1,arr2))
print(arr3)

[[ 1  2  3  3  6  9]
 [ 4  5  6 12 15 18]
 [ 7  8  9 21 24 27]]


In the preceding code, two arrays are stacked horizontally along the x axis. The
concatenate() function can also be used to generate the horizontal stacking
with axis parameter value 1:


In [56]:
arr4=np.concatenate((arr1,arr2),axis=1)
print(arr4)

[[ 1  2  3  3  6  9]
 [ 4  5  6 12 15 18]
 [ 7  8  9 21 24 27]]


In [57]:
#vertical stacking
arr5=np.vstack((arr1,arr2))
print(arr5)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [58]:
#using concatenate
arr6=np.concatenate((arr1,arr2),axis=0)

In [59]:
arr6

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

# depth Stacking
In depth stacking, the same dimensional arrays are joined along
with a third axis (depth) using the dstack() function. Let's see the following
example:

In [60]:
arr7=np.dstack((arr1,arr2))
print(arr7)

[[[ 1  3]
  [ 2  6]
  [ 3  9]]

 [[ 4 12]
  [ 5 15]
  [ 6 18]]

 [[ 7 21]
  [ 8 24]
  [ 9 27]]]


Column stacking: Column stacking stacks multiple sequence one-dimensional
arrays as columns into a single two-dimensional array. Let's see an example of
column stacking:


In [61]:
arr1=np.arange(4,7)
arr1

array([4, 5, 6])

In [62]:
arr2=2*arr1
print(arr2)

[ 8 10 12]


In [63]:
arrcolstack=np.column_stack((arr1,arr2))
print(arrcolstack)

[[ 4  8]
 [ 5 10]
 [ 6 12]]


Row stacking: Row stacking stacks multiple sequence one-dimensional arrays as
rows into a single two-dimensional arrays. Let's see an example of row stacking

In [64]:
arrrowstack=np.row_stack((arr1,arr2))
print(arrrowstack)

[[ 4  5  6]
 [ 8 10 12]]


# partioning  numpy arrays opposite of stack

In [65]:
arr=np.arange(1,10).reshape(3,3)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [66]:
arr_hor_split=np.hsplit(arr,3)

In [67]:
arr_hor_split

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

the hsplit(arr, 3) function divides the array into three
sub-arrays. Each part is a column of the original array.

Vertical splitting: In vertical split, the given array is divided into N equal subarrays along the vertical axis using the vsplit() and split() functions. The
split function with axis=0 performs the same operation as the vsplit()
function:

In [68]:
arr_ver_split=np.vsplit(arr,3)

In [69]:
print(arr_ver_split)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [70]:
# split with axis=0

In [72]:
arr_split=np.split(arr,3,axis=0)

In [73]:
arr_split

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [74]:
#split with axis=1

In [75]:
arr_split=np.split(arr,3,axis=1)

In [76]:
arr_split

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [77]:
# changing the data type of numpy arrays

In [78]:
arr=np.arange(1,10).reshape(3,3)
print('integer array',arr)

integer array [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [80]:
#change datatype
arr=arr.astype(float)
arr#float array

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [81]:
arr.dtype

dtype('float64')

In [82]:
# convert numpy array to python list
arr=arr.tolist()
print(arr)

[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]]


# creating numpy views and copies

Some of the Python functions return either a copy or a view of the input array. A Python
copy stores the array in another location while a view uses the same memory content. This
means copies are separate objects and treated as a deep copy in Python. Views are the
original base array and are treated as a shallow copy. Here are some properties of copies
and views:

Modifications in a view affect the original data whereas modifications in a copy
do not affect the original array.
Views use the concept of shared memory.
Copies require extra space compared to views.
Copies are slower than views.

In [83]:
arr=np.arange(1,5).reshape(2,2)

In [84]:
arr

array([[1, 2],
       [3, 4]])

In [85]:
# create no copy only assignment
arr_no_copy=arr

In [86]:
#create deep copy
arr_copy=arr.copy()

In [87]:
#create shallow copy using view
arr_view=arr.view()

In [88]:
print("Original Array: ",id(arr))
print("Assignment: ",id(arr_no_copy))
print("Deep Copy: ",id(arr_copy))
print("Shallow Copy(View): ",id(arr_view))

Original Array:  2536206730704
Assignment:  2536206730704
Deep Copy:  2538320734224
Shallow Copy(View):  2538320073808


In [89]:
arr[1]=[98,99]

print('view array',arr_view)

print('copyarray',arr_copy)

view array [[ 1  2]
 [98 99]]
copyarray [[1 2]
 [3 4]]


In the preceding example, we can conclude from the results that the view is the original
array. The values changed when we updated the original array and the copy is a separate
object because its values remain the same.

# Slicing numpy arrays

Slicing in NumPy is similar to Python lists. Indexing prefers to select a single value while
slicing is used to select multiple values from an array.
NumPy arrays also support negative indexing and slicing. Here, the negative sign indicates
the opposite direction and indexing starts from the right-hand side with a starting value of
-1:


In [91]:
arr=np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [92]:
arr[3:6]

array([3, 4, 5])

In [93]:
arr[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [95]:
arr[-1:]

array([9])

# Boolean and fancy indexing 

In [97]:
arr=np.arange(21,41,2)
print(arr)

[21 23 25 27 29 31 33 35 37 39]


Indexing techniques help us to select and filter elements from a NumPy array. In this
section, we will focus on Boolean and fancy indexing. Boolean indexing uses a Boolean
expression in the place of indexes (in square brackets) to filter the NumPy array. This
indexing returns elements that have a true value for the Boolean expression:


In [98]:
# boolean indexing
print(arr[arr>30])

[31 33 35 37 39]


Fancy indexing is a special type of indexing in which elements of an array are selected by
an array of indices. This means we pass the array of indices in brackets. Fancy indexing also
supports multi-dimensional arrays. This will help us to easily select and modify a complex
multi-dimensional set of arrays. Let's see an example as follows to understand fancy
indexing:


In [100]:
arr=np.arange(1,21).reshape(5,4)

In [101]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [102]:
# Selecting 2nd and 3rd row
arr[[1,2]]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [103]:
# Selecting 3nd and 4th row
arr[[2,3]]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [111]:
arr[[2,3],[0,1]]

array([ 9, 14])

# broadcasting Arrays

Python lists do not support direct vectorizing arithmetic operations. NumPy offers a fastervectorized array operation compared to Python list loop-based operations. Here, all the
looping operations are performed in C instead of Python, which makes it faster.
Broadcasting functionality checks a set of rules for applying binary functions, such as
addition, subtraction, and multiplication, on different shapes of an array.

In [113]:
arr1=np.arange(1,5).reshape(2,2)
print(arr1)

[[1 2]
 [3 4]]


In [115]:
arr2=np.arange(5,9).reshape(2,2)
arr2

array([[5, 6],
       [7, 8]])

In [117]:
# Add two matrices
print(arr1+arr2)

[[ 6  8]
 [10 12]]


In [118]:
# Multiply two matrices
print(arr1*arr2)

[[ 5 12]
 [21 32]]


In the preceding example, two matrices were multiplied. Let's perform addition and
multiplication with a scalar value:

In [119]:
# add sclar value
arr1+3


array([[4, 5],
       [6, 7]])

In [120]:
# multiply with scalar value
arr1*3

array([[ 3,  6],
       [ 9, 12]])